/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author haroon traders
 */
public class Hangman_Med extends javax.swing.JFrame {

    /**
     * Creates new form Hangman_Med
     */
    public Hangman_Med() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hangman_jPanel2 = new javax.swing.JPanel();
        word1 = new javax.swing.JLabel();
        word2 = new javax.swing.JLabel();
        word3 = new javax.swing.JLabel();
        word4 = new javax.swing.JLabel();
        word5 = new javax.swing.JLabel();
        chance_label = new javax.swing.JLabel();
        life = new javax.swing.JLabel();
        Keyboard_jPanel1 = new javax.swing.JPanel();
        a = new javax.swing.JButton();
        b = new javax.swing.JButton();
        c = new javax.swing.JButton();
        d = new javax.swing.JButton();
        e = new javax.swing.JButton();
        f = new javax.swing.JButton();
        g = new javax.swing.JButton();
        h = new javax.swing.JButton();
        i = new javax.swing.JButton();
        j = new javax.swing.JButton();
        k = new javax.swing.JButton();
        l = new javax.swing.JButton();
        m = new javax.swing.JButton();
        n = new javax.swing.JButton();
        o = new javax.swing.JButton();
        p = new javax.swing.JButton();
        q = new javax.swing.JButton();
        r = new javax.swing.JButton();
        s = new javax.swing.JButton();
        t = new javax.swing.JButton();
        u = new javax.swing.JButton();
        v = new javax.swing.JButton();
        w = new javax.swing.JButton();
        x = new javax.swing.JButton();
        y = new javax.swing.JButton();
        z = new javax.swing.JButton();
        Catagery_jPanel1 = new javax.swing.JPanel();
        namebtn = new javax.swing.JButton();
        anibtn = new javax.swing.JButton();
        placebtn = new javax.swing.JButton();
        colorbtn = new javax.swing.JButton();
        fruitbtn = new javax.swing.JButton();
        Display_Hangman = new javax.swing.JPanel();
        circle = new javax.swing.JLabel();
        body = new javax.swing.JLabel();
        r_leg = new javax.swing.JLabel();
        r_arm = new javax.swing.JLabel();
        l_leg = new javax.swing.JLabel();
        l_arm = new javax.swing.JLabel();
        hintbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        Hangman_jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true));
        Hangman_jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        word1.setBackground(new java.awt.Color(243, 243, 243));
        word1.setText("______");
        word1.setAlignmentY(0.0F);
        Hangman_jPanel2.add(word1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 41));

        word2.setBackground(new java.awt.Color(243, 243, 243));
        word2.setText("______");
        word2.setAlignmentY(0.0F);
        Hangman_jPanel2.add(word2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 41));

        word3.setBackground(new java.awt.Color(243, 243, 243));
        word3.setText("______");
        word3.setAlignmentY(0.0F);
        Hangman_jPanel2.add(word3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, 41));

        word4.setBackground(new java.awt.Color(243, 243, 243));
        word4.setText("______");
        word4.setAlignmentY(0.0F);
        Hangman_jPanel2.add(word4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, -1, 41));

        word5.setBackground(new java.awt.Color(243, 243, 243));
        word5.setText("______");
        word5.setAlignmentY(0.0F);
        Hangman_jPanel2.add(word5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, 41));

        chance_label.setText("CHANCES : ");
        Hangman_jPanel2.add(chance_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, 10));

        life.setText("4");
        Hangman_jPanel2.add(life, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 10, -1));

        Keyboard_jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a.setText("A");
        Keyboard_jPanel1.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 29, 40, -1));

        b.setText("B");
        Keyboard_jPanel1.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 29, 40, -1));

        c.setText("C");
        Keyboard_jPanel1.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 29, 40, -1));

        d.setText("D");
        Keyboard_jPanel1.add(d, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 29, 40, -1));

        e.setText("E");
        Keyboard_jPanel1.add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 29, 40, -1));

        f.setText("F");
        Keyboard_jPanel1.add(f, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 29, 40, -1));

        g.setText("G");
        Keyboard_jPanel1.add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 29, 40, -1));

        h.setText("H");
        Keyboard_jPanel1.add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 29, 40, -1));

        i.setText("I");
        Keyboard_jPanel1.add(i, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 58, 40, -1));

        j.setText("J");
        Keyboard_jPanel1.add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 58, 40, -1));

        k.setText("K");
        Keyboard_jPanel1.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 58, 40, -1));

        l.setText("L");
        Keyboard_jPanel1.add(l, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 58, 40, -1));

        m.setText("M");
        Keyboard_jPanel1.add(m, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 58, 40, -1));

        n.setText("N");
        Keyboard_jPanel1.add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 58, 40, -1));

        o.setText("O");
        Keyboard_jPanel1.add(o, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 58, 40, -1));

        p.setText("P");
        Keyboard_jPanel1.add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 58, 40, -1));

        q.setText("Q");
        Keyboard_jPanel1.add(q, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 87, 40, -1));

        r.setText("R");
        Keyboard_jPanel1.add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 87, 40, -1));

        s.setText("S");
        Keyboard_jPanel1.add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 87, 40, -1));

        t.setText("T");
        Keyboard_jPanel1.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 87, 40, -1));

        u.setText("U");
        Keyboard_jPanel1.add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 87, 40, -1));

        v.setText("V");
        Keyboard_jPanel1.add(v, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 87, 40, -1));

        w.setText("W");
        Keyboard_jPanel1.add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 87, 40, -1));

        x.setText("X");
        Keyboard_jPanel1.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 87, 40, -1));

        y.setText("Y");
        Keyboard_jPanel1.add(y, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 116, 40, -1));

        z.setText("Z");
        Keyboard_jPanel1.add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 116, 40, -1));

        Catagery_jPanel1.setForeground(new java.awt.Color(7, 0, 0));
        Catagery_jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namebtn.setText(" NAME");
        Catagery_jPanel1.add(namebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        anibtn.setText("ANIMAL");
        anibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anibtnActionPerformed(evt);
            }
        });
        Catagery_jPanel1.add(anibtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 6, -1, -1));

        placebtn.setText("PLACE");
        Catagery_jPanel1.add(placebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 6, -1, -1));

        colorbtn.setText("COLOR");
        Catagery_jPanel1.add(colorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 6, -1, -1));

        fruitbtn.setText("FRUIT");
        Catagery_jPanel1.add(fruitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 6, -1, -1));

        Display_Hangman.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        circle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/circle.png"))); // NOI18N
        Display_Hangman.add(circle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        body.setIcon(new javax.swing.ImageIcon(getClass().getResource("/line2.png"))); // NOI18N
        Display_Hangman.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 30, 70));

        r_leg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagonalline.png"))); // NOI18N
        Display_Hangman.add(r_leg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 30, 50));

        r_arm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diagonalline.png"))); // NOI18N
        Display_Hangman.add(r_arm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 30, 20));

        l_leg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tdiagonalline.png"))); // NOI18N
        Display_Hangman.add(l_leg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 30, 50));

        l_arm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Tdiagonalline.png"))); // NOI18N
        Display_Hangman.add(l_arm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 30, 20));

        hintbtn.setText("HINT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Catagery_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Keyboard_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(Display_Hangman, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hintbtn)))))
                .addGap(12, 12, 12))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Hangman_jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Catagery_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Hangman_jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Keyboard_jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hintbtn)
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Display_Hangman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anibtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anibtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hangman_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hangman_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hangman_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hangman_Med.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hangman_Med().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Catagery_jPanel1;
    private javax.swing.JPanel Display_Hangman;
    private javax.swing.JPanel Hangman_jPanel2;
    private javax.swing.JPanel Keyboard_jPanel1;
    private javax.swing.JButton a;
    private javax.swing.JButton anibtn;
    private javax.swing.JButton b;
    private javax.swing.JLabel body;
    private javax.swing.JButton c;
    private javax.swing.JLabel chance_label;
    private javax.swing.JLabel circle;
    private javax.swing.JButton colorbtn;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton f;
    private javax.swing.JButton fruitbtn;
    private javax.swing.JButton g;
    private javax.swing.JButton h;
    private javax.swing.JButton hintbtn;
    private javax.swing.JButton i;
    private javax.swing.JButton j;
    private javax.swing.JButton k;
    private javax.swing.JButton l;
    private javax.swing.JLabel l_arm;
    private javax.swing.JLabel l_leg;
    private javax.swing.JLabel life;
    private javax.swing.JButton m;
    private javax.swing.JButton n;
    private javax.swing.JButton namebtn;
    private javax.swing.JButton o;
    private javax.swing.JButton p;
    private javax.swing.JButton placebtn;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JLabel r_arm;
    private javax.swing.JLabel r_leg;
    private javax.swing.JButton s;
    private javax.swing.JButton t;
    private javax.swing.JButton u;
    private javax.swing.JButton v;
    private javax.swing.JButton w;
    private javax.swing.JLabel word1;
    private javax.swing.JLabel word2;
    private javax.swing.JLabel word3;
    private javax.swing.JLabel word4;
    private javax.swing.JLabel word5;
    private javax.swing.JButton x;
    private javax.swing.JButton y;
    private javax.swing.JButton z;
    // End of variables declaration//GEN-END:variables
}
